name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download 7Zip
      run: |
        bitsadmin /transfer wcb /priority high https://www.7-zip.org/a/7z1900.exe 7z1900.exe
        start 7z1900.exe
    - name: Download DevKitPro Tools
      run: |
        bitsadmin /transfer wcb /priority high https://wii.leseratte10.de/devkitPro/devkitARM/r20%20(2007)/devkitARM_r20-win32.exe devkitARM_r20-win32.exe
        start devkitARM_r20-win32.exe
